### ISSUE TITLE
BUG: Sidebar is not fixed at the left side of the screen

### ISSUE THREAD

**Issue by zeddrix** [philipp-tailor/svelte_sidebar#410]
Hi Mr. @philipp-tailor. I'm using sveltekit and did this...

```
import Sidebar from 'svelte_sidebar'

const props = {...}

<Sidebar {...props} />
```

...inside my __layout.svelte file. The sidebar is showing. But the problem is that when I put this Sidebar component (for example, at the top of my other elements and components), it just goes above all my other components; it doesn't get **fixed** at the side like what's shown in the playground site.

**Comment by philipp-tailor** [comment]
Hello @zeddrix, thank you for trying out this package. Sorry for not answering earlier, I was on vacation without internet access. I hope that my answer still comes in time:

As you can see [here](https://github.com/philipp-tailor/svelte_sidebar/blob/e16d8ae12f80b63ffcca26e16a6c3905b922d338/src/App.svelte#L92), on the playground, the whole document body is laid out side-by-side in a `flexbox`. The reason is that I can't anticipate the exact placements / layouts in which users of the package might want to use it.
So if you place `<Sidebar/>` and your main page content container - let's say a - `<main>...</main>` inside an element with `display: flex;`, and define appropriate `flex-grow` / `flex-shrink` / `flex-basis` values to the `<Sidebar/>` like the [example values used in the playground](https://github.com/philipp-tailor/svelte_sidebar/blob/e16d8ae12f80b63ffcca26e16a6c3905b922d338/src/App.svelte#L102-L104), you should be good to go.

**Comment by zeddrix** [comment]
Thank you @philipp-tailor! Really appreciate the help and reply!
